# Generated by Django 5.2.6 on 2025-10-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Youtube', 'Youtube'), ('Google', 'Google'), ('Newsletter', 'Newsletter')], max_length=100, null=True),
        ),
    ]
